### ISSUE TITLE
Compilation of ruby binding fails on ruby 1.9

### ISSUE THREAD

**Issue by manveru** [sck/localmemcache#1]
The C code still uses RARRAY(r)->ptr and the len equivalent, i tried patching it but I'm not 100% sure whether this will actually work on Ruby 1.8.x since my C knowledge is rather limited.

http://pastr.it/16152 is a possible patch

**Comment by sck** [comment]
Should be fixed now with 0.4.1.

**Comment by manveru** [comment]
Yeah, works fine, thanks :)
