### ISSUE TITLE
sem_open: Permission denied

### ISSUE THREAD

**Issue by MadBomber** [sck/localmemcache#2]
Environment:  Two user accounts, same computer, all Ruby.  Fedora Core 11. Ruby 1.8.7-p302.

User A creates the LMC.  User A has multiple processes all successfully reading and writing the LMC.

User B gets the LocalMemCache::LockError exception when he tries to do LocalMemCache::SharedObjectStorage.new with the same :namespace value and LMC_NAMESPACES_ROOT_PATH

Is my expectation wrong?  Is LMC only for a single user?

**Comment by sck** [comment]
Hey MadBomber,

what's the umask of user A?  Normally it should be just a matter of the umask whether another user can access a namespace... On my gentoo linux I can see the semaphore lock files in ``/dev/shm/sem.*''.  If you can find the semaphore file that gives you the permission denied error you can change the permission (it's a normal file).  You also might need to do the same for $LMC_NAMESPACES_ROOT_PATH/<namespace>.lmc

Best,

Sven

**Comment by sck** [comment]
It should read ``$LMC_NAMESPACES_ROOT_PATH/$(namespace).lmc'' above but GitHub removed part of it...

**Comment by MadBomber** [comment]
Sven, I had to setup sudo'er capability for the users.
They have wrapped their Ruby call to new in a 
begin; rescue; rescue; end block.  One rescue deals with
the permissions on the *.lmc sparse file while the other
deals with the permissions on the sem.* file using
a system call to sudo chmod 664 on tthe files.  This all 
because they did not want to change their umask settings.
I have not heard back from them so I'm assuming this is working.
Thanks for the help.  I will check back with them next week
to ensure this work-around fixed their issue.

Dewayne
  o-*
